blogicum/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path(
        'category/<slug:category_slug>/',
        views.CategoryListView.as_view(),
        name='category_posts'
    ),
    path(
        'posts/create/',
        views.PostCreateView.as_view(),
        name='create_post'
    ),
    path(
        'posts/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'posts/<int:pk>/edit/',
        views.PostUpdateView.as_view(),
        name='edit_post'
    ),
    path(
        'posts/<int:pk>/delete/',
        views.PostDeleteView.as_view(),
        name='delete_post'
    ),
    path(
        'posts/<int:pk>/comment/',
        views.CommentCreateView.as_view(),
        name='add_comment'
    ),
    path(
        'posts/<int:pk>/edit_comment/<int:comment_pk>',
        views.CommentUpdateView.as_view(),
        name='edit_comment'
    ),
    path(
        'posts/<int:pk>/delete_comment/<int:comment_pk>',
        views.CommentDeleteView.as_view(),
        name='delete_comment'
    ),
    path(
        'profile/<slug:username>/',
        views.UserListView.as_view(),
        name='profile'
    ),
    path(
        'edit_profile/',
        views.ProfileUpdateView.as_view(),
        name='edit_profile'
    ),
]

blogicum/blogicum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView

handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.server_error'

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('blog:index'),
        ),
        name='registration',
    ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogicum/blog/models.py
from core.models import PublishedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Category(PublishedModel):
    title = models.CharField(
        max_length=256,
        verbose_name='Title'
    )
    description = models.TextField(verbose_name='Description')
    slug = models.SlugField(
        unique=True,
        verbose_name='id',
        help_text=(
            'id for URL; '
            'Latin letters, numbers, hyphen, and underscore are allowed.'
        )
    )

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Location(PublishedModel):
    name = models.CharField(
        max_length=256,
        verbose_name='Location name'
    )

    class Meta:
        verbose_name = 'location'
        verbose_name_plural = 'Locations'

    def __str__(self):
        return self.name


class Post(PublishedModel):
    title = models.CharField(
        max_length=256,
        verbose_name='Title'
    )
    text = models.TextField(verbose_name='Text')
    pub_date = models.DateTimeField(
        verbose_name='Time and date of publication',
        help_text=(
            'If you set a date and time in the future, '
            'you can make scheduled publications.'
        )
    )
    image = models.ImageField(
        'Image', upload_to='post_images', blank=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Pulication author'
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Location'
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts',
        verbose_name='Category'
    )

    class Meta:
        verbose_name = 'publication'
        verbose_name_plural = 'Publications'

    def __str__(self):
        return self.title


class Comment(PublishedModel):
    text = models.TextField('Comment text')
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'comment'
        verbose_name_plural = 'Comments'
        ordering = ('created_at',)

blogicum/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone

from .models import Comment, Post


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['pub_date'].initial = timezone.localtime(
            timezone.now()).strftime('%Y-%m-%dT%H:%M')

    class Meta:
        model = Post
        fields = ['title', 'text', 'pub_date', 'image', 'location', 'category']
        widgets = {
            'pub_date': forms.DateTimeInput(attrs={'type': 'datetime-local'})
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blogicum/blog/views.py
from blog.forms import CommentForm, PostForm, UserForm
from blog.models import Category, Comment, Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from blogicum.settings import MAX_POSTS_ON_PAGE


class AuthorCheckMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author != request.user:
            return redirect('blog:post_detail', pk=self.kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)


class IndexListView(ListView):
    model = Post
    template_name = 'blog/index.html'
    paginate_by = MAX_POSTS_ON_PAGE
    ordering = ['-pub_date', 'title']

    def get_queryset(self):
        now = timezone.now()
        queryset = super().get_queryset().select_related(
            'location', 'author', 'category'
        ).filter(
            pub_date__lte=now,
            is_published=True,
            category__is_published=True
        ).annotate(comment_count=Count('comments'))
        return queryset


class UserListView(ListView):
    model = Post
    template_name = 'blog/profile.html'
    paginate_by = MAX_POSTS_ON_PAGE
    ordering = ['-pub_date', 'title']

    def get_queryset(self):
        username = self.kwargs['username']
        profile = get_object_or_404(User, username=username)

        if profile == self.request.user:
            # all posts for the current user's profile
            queryset = super().get_queryset().select_related(
                'location', 'author', 'category'
            ).filter(
                author=profile
            ).annotate(
                comment_count=Count('comments')
            )
            return queryset
        else:
            # published posts for other users
            now = timezone.now()
            return super().get_queryset().select_related(
                'location', 'author', 'category'
            ).filter(
                author=profile,
                pub_date__lte=now,
                is_published=True,
                category__is_published=True
            ).annotate(comment_count=Count('comments'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.kwargs['username']
        profile = get_object_or_404(User, username=username)
        context['profile'] = profile
        return context


class CategoryListView(ListView):
    model = Category
    template_name = 'blog/category.html'
    paginate_by = MAX_POSTS_ON_PAGE

    def get_queryset(self):
        self.category = get_object_or_404(
            Category,
            slug=self.kwargs['category_slug'],
            is_published=True
        )

        now = timezone.now()

        return self.category.posts.filter(
            is_published=True,
            pub_date__lte=now
        ).annotate(
            comment_count=Count('comments')
        ).order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'blog:profile', kwargs={'username': self.request.user.username}
        )


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        post = self.object

        # check is_published and author
        if not post.is_published or (
            post.category and not post.category.is_published
        ):
            if request.user.is_authenticated and request.user == post.author:
                return super().dispatch(request, *args, **kwargs)
            raise Http404('Page not found')

        # check pub_time and author
        now = timezone.now()

        if post.pub_date > now and request.user != post.author:
            raise Http404('Page not found')

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        context['comments'] = self.object.comments.all().order_by(
            'created_at'
        )
        return context


class PostUpdateView(AuthorCheckMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create.html'

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'pk': self.kwargs['pk']}
        )


class PostDeleteView(AuthorCheckMixin, DeleteView):
    model = Post
    template_name = 'blog/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = PostForm(instance=self.object)
        return context

    def get_success_url(self):
        return reverse_lazy(
            'blog:profile', kwargs={'username': self.request.user}
        )


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'

    def dispatch(self, request, *args, **kwargs):
        self.commented_post = get_object_or_404(Post, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = self.commented_post
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'pk': self.commented_post.pk}
        )


class CommentUpdateView(AuthorCheckMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_pk'

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'pk': self.kwargs['pk']}
        )


class CommentDeleteView(AuthorCheckMixin, DeleteView):
    model = Comment
    template_name = 'blog/comment.html'
    pk_url_kwarg = 'comment_pk'

    def get_success_url(self):
        return reverse_lazy(
            'blog:post_detail', kwargs={'pk': self.kwargs['pk']}
        )


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserForm
    template_name = 'blog/user.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy(
            'blog:profile', kwargs={'username': self.object.username}
        )

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Publications in a category {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Publications in a category - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/comment.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit_comment/' in request.path %}
    Edit comment
  {% else %}
    Delete comment
  {% endif %}
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <div class="col d-flex justify-content-center">
      <div class="card" style="width: 40rem;">
        <div class="card-header">
          {% if '/edit_comment/' in request.path %}
            Edit comment
          {% else %}
            Delete comment
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"
            {% if '/edit_comment/' in request.path %}
              action="{% url 'blog:edit_comment' comment.post_id comment.id %}"
            {% endif %}>
            {% csrf_token %}
            {% if not '/delete_comment/' in request.path %}
              {% bootstrap_form form %}
            {% else %}
              <p>{{ comment.text }}</p>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Save" %}
          </form>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

blogicum/templates/blog/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Edit publication
  {% elif "/delete/" in request.path %}
    Delete publication
  {% else %}
    Add publication
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Edit publication
        {% elif '/delete/' in request.path %}
          Delete publication
        {% else %}
          Add publication
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2"
                       src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>
                {{ form.instance.pub_date|date:"d E Y" }} |
                {% if form.instance.location.name and form.instance.location.is_published %}
                  {{ form.instance.location.name }}
                {% else %}
                  Planet Earth
                {% endif %}
                <br>
                <h3>{{ form.instance.title }}</h3>
                <p>{{ form.instance.text|linebreaksbr }}</p>
              </article>
            {% endif %}
            {% bootstrap_button button_type="submit" content="Save" %}
          </form>
        </div>
      </div>
    </div>
  {% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
  {{ post.title }} |
  {% if post.location and post.location.is_published %}
    {{ post.location.name }}
  {% else %}
    Planet Earth
  {% endif %}
  |
  {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if post.image %}
          <a href="{{ post.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block"
                 src="{{ post.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not post.is_published %}
              <p class="text-danger">Post is removed from published by admin</p>
            {% elif not post.category.is_published %}
              <p class="text-danger">Category removed from published by admin</p>
            {% endif %}
            {{ post.pub_date|date:"d E Y, H:i" }} |
            {% if post.location and post.location.is_published %}
              {{ post.location.name }}
            {% else %}
              Planet Earth
            {% endif %}
            <br>
            From author <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a> in
            category
            {% include "includes/category_link.html" %}
          </small>
        </h6>
        <p class="card-text">{{ post.text|linebreaksbr }}</p>
        {% if user == post.author %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted"
               href="{% url 'blog:edit_post' post.id %}"
               role="button">Edit publication</a>
            <a class="btn btn-sm text-muted"
               href="{% url 'blog:delete_post' post.id %}"
               role="button">Delete publication</a>
          </div>
        {% endif %}
        {% include "includes/comments.html" %}
      </div>
    </div>
  </div>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Publications feed
{% endblock %}
{% block content %}
  {% for post in page_obj %}
    <article class="mb-5">
      {% include "includes/post_card.html" %}
    </article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/profile.html
{% extends "base.html" %}
{% block title %}Page of user {{ profile }}{% endblock %}
{% block content %}
  <h1 class="mb-5 text-center ">Page of user: {{ profile }}</h1>
  <small>
    <ul class="list-group list-group-horizontal justify-content-center mb-3">
      <li class="list-group-item text-muted">
        User name:
        {% if profile.get_full_name %}
          {{ profile.get_full_name }}
        {% else %}
          not specified
        {% endif %}
      </li>
      <li class="list-group-item text-muted">Registration: {{ profile.date_joined }}</li>
      <li class="list-group-item text-muted">
        Role:
        {% if profile.is_staff %}
          Admin
        {% else %}
          User
        {% endif %}
      </li>
    </ul>
    <ul class="list-group list-group-horizontal justify-content-center">
      {% if user.is_authenticated and request.user == profile %}
        <a class="btn btn-sm text-muted" href="{% url 'blog:edit_profile' %}">Edit profile</a>
        <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Change password</a>
      {% endif %}
    </ul>
  </small>
  <br>
  {% if page_obj %}<h3 class="mb-5 text-center">User's publications:</h3>{% endif %}
  {% for post in page_obj %}
    <article class="mb-5">{% include "includes/post_card.html" %}</article>
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

blogicum/templates/blog/user.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}Edit profile{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">Change profile details - {{ request.user }}</div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Change" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}